//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseManual = new HashSet<CourseManual>();
            this.InstructorCourse = new HashSet<InstructorCourse>();
            this.TopicsInCourse = new HashSet<TopicsInCourse>();
        }
    
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual ICollection<CourseManual> CourseManual { get; set; }
        public virtual ICollection<InstructorCourse> InstructorCourse { get; set; }
        public virtual ICollection<TopicsInCourse> TopicsInCourse { get; set; }
    }
}
