//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exams
    {
        public Exams()
        {
            this.DepartmentsExam = new HashSet<DepartmentsExam>();
            this.NewDateExamForPermittedStudent = new HashSet<NewDateExamForPermittedStudent>();
            this.QuestionsInExam = new HashSet<QuestionsInExam>();
            this.StudentAnswerQuestionInExam = new HashSet<StudentAnswerQuestionInExam>();
            this.StudentPermissionInExam = new HashSet<StudentPermissionInExam>();
        }
    
        public int Exam_Id { get; set; }
        public string Exam_Name { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<int> Number_Of_Questions { get; set; }
        public Nullable<int> Ins_Id { get; set; }
        public Nullable<bool> Exam_Corrected { get; set; }
        public Nullable<int> Exam_Duration { get; set; }
        public Nullable<int> PlatformIntake_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PlatfromIntake PlatfromIntake { get; set; }
        public virtual ICollection<DepartmentsExam> DepartmentsExam { get; set; }
        public virtual ICollection<NewDateExamForPermittedStudent> NewDateExamForPermittedStudent { get; set; }
        public virtual ICollection<QuestionsInExam> QuestionsInExam { get; set; }
        public virtual ICollection<StudentAnswerQuestionInExam> StudentAnswerQuestionInExam { get; set; }
        public virtual ICollection<StudentPermissionInExam> StudentPermissionInExam { get; set; }
    }
}
