//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public Notifications()
        {
            this.Employee = new HashSet<Employee>();
            this.StudentBasicData = new HashSet<StudentBasicData>();
            this.Employee1 = new HashSet<Employee>();
        }
    
        public int Notification_Id { get; set; }
        public string Notification_Text { get; set; }
        public Nullable<bool> Is_Read { get; set; }
        public Nullable<System.DateTime> Creation_Time { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<StudentBasicData> StudentBasicData { get; set; }
        public virtual ICollection<Employee> Employee1 { get; set; }
    }
}
