//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatfromIntake
    {
        public PlatfromIntake()
        {
            this.DepartmentsExam = new HashSet<DepartmentsExam>();
            this.Exams = new HashSet<Exams>();
            this.StudentBasicData = new HashSet<StudentBasicData>();
            this.TrackManager = new HashSet<TrackManager>();
            this.TrackSupervisor = new HashSet<TrackSupervisor>();
        }
    
        public int PlatformIntakeID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> SubTrackID { get; set; }
        public Nullable<int> ProgramIntakeID { get; set; }
        public Nullable<int> OwnedBy { get; set; }
        public string GraduateProfile { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<DepartmentsExam> DepartmentsExam { get; set; }
        public virtual ICollection<Exams> Exams { get; set; }
        public virtual ProgramIntake ProgramIntake { get; set; }
        public virtual subTrack subTrack { get; set; }
        public virtual ICollection<StudentBasicData> StudentBasicData { get; set; }
        public virtual ICollection<TrackManager> TrackManager { get; set; }
        public virtual ICollection<TrackSupervisor> TrackSupervisor { get; set; }
    }
}
