//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsInExam
    {
        public int Ques_Id { get; set; }
        public int Exam_Id { get; set; }
        public Nullable<int> Degree { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Question Question { get; set; }
    }
}
