//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionAnswer
    {
        public int Ques_Id { get; set; }
        public int Answer_Id { get; set; }
        public string Answer_Content { get; set; }
        public Nullable<bool> Is_It_RightAnswer { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
