//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPermissionInExam
    {
        public int Std_Id { get; set; }
        public int Exam_Id { get; set; }
        public Nullable<System.DateTime> Permission_Date { get; set; }
    
        public virtual StudentBasicData StudentBasicData { get; set; }
        public virtual Exams Exams { get; set; }
    }
}
