//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subTrack
    {
        public subTrack()
        {
            this.PlatfromIntake = new HashSet<PlatfromIntake>();
        }
    
        public int subtrackID { get; set; }
        public string subtrackName { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<PlatfromIntake> PlatfromIntake { get; set; }
    }
}
