//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseEvaluationItem
    {
        public CourseEvaluationItem()
        {
            this.EvaluationCriterias = new HashSet<EvaluationCriteria>();
        }
    
        public int EvalID { get; set; }
        public string EvalDesc { get; set; }
    
        public virtual ICollection<EvaluationCriteria> EvaluationCriterias { get; set; }
    }
}
