//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesDataView
    {
        public string CourseName { get; set; }
        public string programName { get; set; }
        public Nullable<int> IntakeNo { get; set; }
        public int CourseID { get; set; }
        public int CourseInstanceID { get; set; }
        public int courseManualID { get; set; }
        public int TrackManualID { get; set; }
        public int programId { get; set; }
        public int ProgramIntakeID { get; set; }
        public int IntakeID { get; set; }
    }
}
