//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Platforms = new HashSet<Platform>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string ArabicName { get; set; }
        public Nullable<int> Flag { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
    
        public virtual ICollection<Platform> Platforms { get; set; }
    }
}
