//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_metadata
    {
        public int EmployeeID { get; set; }
        public string InstructorName { get; set; }
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public int subtrackID { get; set; }
        public string subtrackName { get; set; }
        public int PlatformID { get; set; }
        public string PlatformName { get; set; }
        public int PlatformIntakeID { get; set; }
        public Nullable<int> Department_ID { get; set; }
    }
}
