//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluationiteminstructor
    {
        public int recserial { get; set; }
        public Nullable<int> CourseinstanceID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> evalid { get; set; }
        public Nullable<int> STUDENTID { get; set; }
        public Nullable<System.DateTime> evaluationdate { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<double> it1 { get; set; }
        public byte[] itemgrade { get; set; }
    }
}
