//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationCriteria
    {
        public int ExID { get; set; }
        public Nullable<int> EvalID { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<int> CourseManualID { get; set; }
    
        public virtual CourseEvaluationItem CourseEvaluationItem { get; set; }
        public virtual CourseManual CourseManual { get; set; }
    }
}
