//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalInstructorAuthorization
    {
        public int Ins_Id { get; set; }
        public int Code { get; set; }
        public System.DateTime Expiration_Date { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
