//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentNotification
    {
        public int Student_Id { get; set; }
        public int Notification_Id { get; set; }
        public int Notify_Id { get; set; }
    
        public virtual StudentBasicData StudentBasicData { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
