//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMultiAnswersQuestion
    {
        public System.Guid Std_Answer_Id { get; set; }
        public int Ques_Id { get; set; }
        public string Answer_Content { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual StudentAnswerQuestionInExam StudentAnswerQuestionInExam { get; set; }
    }
}
