//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Enrollment
    {
        public int StudentEnrollmentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CourseInstanceDetailsID { get; set; }
    
        public virtual CourseInstanceDetail CourseInstanceDetail { get; set; }
        public virtual StudentBasicData StudentBasicData { get; set; }
    }
}
