//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.PlatfromIntakes = new HashSet<PlatfromIntake>();
        }
    
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public string arabicname { get; set; }
        public System.Guid msrepl_tran_version { get; set; }
        public Nullable<int> trainbranchid { get; set; }
    
        public virtual ICollection<PlatfromIntake> PlatfromIntakes { get; set; }
    }
}
