//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramIntake
    {
        public ProgramIntake()
        {
            this.PlatfromIntakes = new HashSet<PlatfromIntake>();
        }
    
        public int IntakeID { get; set; }
        public int ProgramID { get; set; }
        public int ProgramIntakeID { get; set; }
    
        public virtual ICollection<PlatfromIntake> PlatfromIntakes { get; set; }
        public virtual program program { get; set; }
    }
}
